import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import DefaultNavbar from '@/components/Navbar/DefaultNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <header className="border-b-2 border-[rgba(0,0,0,0.25)] shadow-sm">
          <DefaultNavbar />
        </header>
        {children}
      </body>
    </html>
  );
}
